namespace ThunderLib.Core
{
    using System;

    /// <summary>
    /// Info about the loaded version of ThunderLib.Core
    /// </summary>
    public static partial class Info
    {
        /// <summary>
        /// The version of ThunderLib.Core currently loaded
        /// </summary>
        public static String versionStr => _version;

  
        /// <summary>
        /// A System.Version that represents the version of ThunderLib.Core currently loaded
        /// </summary>
        public static Version version { get; } = new(versionStr);




        //TODO: This const should be generated by a source gen
        /// <summary>
        /// Internal version string constant. Should not be used unless a constant is specifically needed (like in an attribute)
        /// </summary>
        internal const String _version = "0.0.1.1";
    }
}
